# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.
# The lines in this template starting with the hashtag symbol are
#   instructional comments and can be safely left in the file or
#   ignored.
# For help completing this file, see the "AppSpec File Reference" in the
#   "CodeDeploy User Guide" at
#   https://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/ipo_watchtower
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/AfterInstall.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      runas: ubuntu
